#!/bin/sh

COUNTER=$3
COUNTER=$(( COUNTER * 5 ))

while [ $COUNTER -gt 0 ]
do
        echo $COUNTER seconds remaining in break
        COUNTER=$(( COUNTER - 1 ))
        sleep 1
done

echo "Break Over"